version: "3"
services:
    nginx:
        image: nginx-haufe
        ports:
            - "80:80"
        depends_on: 
            - node    
    node:
        image: node-haufe
        ports:
            - "8080:8080"
        depends_on:
            - mongo
    mongo:
        image: mongo
        container_name: mongodb
        ports:
            - 27017:27017
       



